### ISSUE TITLE
Scoping: Conditions

### ISSUE THREAD

**Issue by krbz999** [krbz999/artichron#7]
Tracking what custom conditions are relevant to the system.

- [x] **Hindered.** The character has one fewer pips on their turn (minimum 1).
- [x] **Burning.** At the start of each round of combat, the character takes 1d12 fire damage for each level of this condition.
- [x] **Bleeding.** At the start of each round of combat, the character takes 1d6 physical damage for each level of this condition (this damage is not resisted).
- [x] **Injured.** The maximum health of the actor is reduced by 5% for each level of this condition. If this reaches 100%, the character is dead. (An item determines how many stacks of this condition it applies at once.)
- [x] #71

### Nice to have
- [ ] Store data on each item to determine how many stacks of a leveled condition they may apply.

**Comment by InnilToo** [comment]
The base idea is that there are two categories, Positive and Negative. Each condition can also stack (there might be exceptions) in either duration, potency, or both.

**Positive**
1. **HP Regeneration** (Health Regen, Health Recovery) - Gradually restores X amount of health points over a set period of time.
2. **Mana Regeneration** (Mana Regen, Mana Recovery) - Gradually replenishes X amount of mana points over a set period of time.
3. **Stamina Regeneration** (Endurance Regen, Stamina Recovery) - Gradually restores X amount of stamina points, over a set period of time.
4. **Shield** (Barrier, Protector) - Provides a temporary shield that absorbs the next damage.
5. **Temporary HP** (Temp HP, Shielding) - Grants additional health points on top of the character’s maximum HP which are lost first when taking damage.
6. **Buff to Attacks** (Attack Boost, Strength Enhance) - Increases the damage output or hit chance of the character's attacks for a duration.
7. **Buff to Movement Speed** (Speed Boost, Acceleration) - Increases the character's movement speed by a specified value for a duration.
8. **Fortified** (Strengthened, Armored) - Increases the character's resistance to physical and magical damage for a duration.
9. **Energized** (Power Surge, Invigorated) - Temporarily reduces the mana cost.
10. **Cloaked** (Stealthed, Invisible) - Temporarily makes the character invisible to enemies, allowing them to avoid detection or get the first strike advantage.
11. **Stability** (Surefooted, Grounded) - The character cannot be moved, knocked back, or otherwise displaced against their will, providing resistance to such effects.

**Negative**
1. **Bleeding** (Hemorrhage, Laceration) - Causes the character to lose health points periodically, representing continuous damage over time.
2. **Blinded** (Vision Loss, Darkened) - Severely reduces the character's ability to see, impacting attack accuracy and movement.
3. **Burning** (Ignite, Flame) - Causes the character to lose health points periodically, representing continuous damage over time.
4. **Charmed** (Beguiled, Enthralled) - Causes the character to be temporarily allied with the enemy.
5. **Confused** (Disoriented, Misled) - Causes the character to lose control, occasionally moving or attacking in random directions or even targeting allies instead of enemies.
6. **Deafened** (Muffled, Silenced) - Prevents the character from hearing, which may affect communication and awareness of surrounding actions or spells.
8. **Decrease to Attacks** (Weakness, Reduction) - Reduces the effectiveness or accuracy of the character’s attacks for a limited time.
9. **Decrease to Movement Speed** (Slowing, Reducing) - Reduces the character’s movement speed by a specified percentage for a limited duration.
10. **Exposed** (Revealed, Unveiled) - Marks the character, revealing them to enemies even if normally hidden or cloaked.
11. **Immobilized** (Rooted, Fixed) - Completely prevents movement but does not prevent actions such as attacks or spell casting.
15. **Muted** (Silenced, Speechless) - Prevents the character from casting spells that require verbal components or communicating verbally.
16 **Pacified** (Neutralized, Disarmed) - Temporarily prevents the character from using any offensive abilities, forcing them to rely on non-combat skills or flee until the effect wears off.
14. **Poisoned** (Toxic, Venomed) - Causes the character to lose health points periodically, representing continuous damage over time.
15. **Restrained** (Bound, Tied) - Completely prevents movement and prevents actions such as attacks or spell casting.
16. **Scared** (Frightened, Terrified) - Causes the character to suffer penalties to actions due to fear, potentially fleeing from threats.
17. **Stun** (Dazed, Incapacitated) - Temporarily incapacitates the character, preventing any movement or action until the stun wears off.
18. **Unconscious** (Comatose, Insensible) - Renders the character completely incapacitated, unable to move, act, or perceive surroundings until revived or restored.
21. **Weakened** (Frail, Debilitated) - Reduces the character’s defensive capabilities, increasing the damage they take from all sources for a period of time.

**Comment by krbz999** [comment]
This is a good list, let's take the ones we like and perfect them, and perhaps add some that also modify certain attributes of the actors.

**Comment by krbz999** [comment]
Once conditions have been figured out, ammo should be able to apply one when used with a weapon.

**Comment by Mythacri** [comment]
Conditions that level up as applied:

Bleeding - Character takes 1d6 damage at the start of each of their turns
Burning - Character takes 1d12 fire damage at the start of each of their turns
Poisoned - Character's attacks do 1 fewer die of damage. Character takes 1d6 damage at the start of their turns
Frozen - Character needs to spend one additional pip to move
Hindered - Character has one fewer pips on their turn (minimum 1)
Injured - Character's maximum hit points is reduced by 10%
Quickened - Character has one additional pip on their turn
Frightened - Character must make Health-Head check or use 1 pip to run away from the enemy this turn
Charmed - Character must make a Health-Head check or use 1 pip to run towards the enemy this turn

Item Conditions
Damaged - Equipments rolls are reduced by 1d4
Blessed - Equipments rolls are increased by 1d4

**Comment by krbz999** [comment]
> 9\. **Exposed** (Revealed, Unveiled) - Marks the character, revealing them to enemies even if normally hidden or cloaked.

Doing this one because it sounds like a challenge.

**Comment by krbz999** [comment]
The levels of a specific attribute can be stored in `Item#flags.artichron.attributes`. Example:
```js
// Setting the level
await item.setFlag("artichron", "attributes.rending", 5);

// Retrieving the level
item.getFlag("artichron", "attributes.rending");
```

There is no UI for this yet. The flag object is used to apply the correct level, still requiring that the item has, e.g., "rending" in `system.attributes.value`. If no specific level is set, then the level is 1.
