### ISSUE TITLE
Allow Items to stack.

### ISSUE THREAD

**Issue by NMyers17** [krbz999/artichron#95]
Currently items all appear as a unique item when adding them to the character sheet. If possible these items should be added to the already available items in the inventory, increasing the quantity of the item and creating a "stack".

Items in stacks should have a way of displaying the quantity of a stack. I'd suggest a small number in the bottom right-hand corner of the items image, which would indicate the current stack level.
![image](https://github.com/user-attachments/assets/75161138-0101-4686-92c7-d69be0f51191)

**Comment by krbz999** [comment]
Adding a unique `system.identifier` property to the item would help here. Been itching to add that regardless. Then dropping an item onto a sheet could find an existing item with the same identifier and increase that items quantity rather than add a new item.

This way, we wouldn't need to compare to a `_stats.compendiumSource` uuid, or match by name and description or other such things. Should still compare the item type.

**Comment by krbz999** [comment]
![image](https://github.com/user-attachments/assets/de2edb4a-efc5-4ee6-a9f2-a42c8d332551)
